//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdeaDatabase.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdeaIntellectualProperty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IdeaIntellectualProperty()
        {
            this.IdeaAttachments = new HashSet<IdeaAttachment>();
        }
    
        public int IntellectualId { get; set; }
        public Nullable<int> IdeaId { get; set; }
        public string RecordId { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> FiledDate { get; set; }
        public string ApplicationNumber { get; set; }
        public string PatentId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> AttachmentCount { get; set; }
        public Nullable<bool> IsAttachment { get; set; }
        public Nullable<int> UserId { get; set; }
        public string InventionReference { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IdeaAttachment> IdeaAttachments { get; set; }
        public virtual Idea Idea { get; set; }
        public virtual User User { get; set; }
    }
}
