//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdeaDatabase.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdeaAttachment
    {
        public int IdeaAttachmentId { get; set; }
        public int IdeaId { get; set; }
        public string AttachedFileName { get; set; }
        public string FileExtention { get; set; }
        public Nullable<long> FileSizeInByte { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string FolderName { get; set; }
        public Nullable<int> IntellectualPropertyId { get; set; }
    
        public virtual Idea Idea { get; set; }
        public virtual IdeaIntellectualProperty IdeaIntellectualProperty { get; set; }
    }
}
