//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdeaDatabase.DataContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IdeaDatabaseDataContext : DbContext
    {
        public IdeaDatabaseDataContext()
            : base("name=IdeaDatabaseDataContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdmSetting> AdmSettings { get; set; }
        public virtual DbSet<EmailTemplate> EmailTemplates { get; set; }
        public virtual DbSet<IdeaAssignment> IdeaAssignments { get; set; }
        public virtual DbSet<IdeaAttachment> IdeaAttachments { get; set; }
        public virtual DbSet<IdeaCategory> IdeaCategories { get; set; }
        public virtual DbSet<IdeaChallenge> IdeaChallenges { get; set; }
        public virtual DbSet<IdeaComment> IdeaComments { get; set; }
        public virtual DbSet<IdeaCommentDiscussion> IdeaCommentDiscussions { get; set; }
        public virtual DbSet<IdeaContributor> IdeaContributors { get; set; }
        public virtual DbSet<Idea> Ideas { get; set; }
        public virtual DbSet<IdeaStatusLog> IdeaStatusLogs { get; set; }
        public virtual DbSet<IdeaSubscriber> IdeaSubscribers { get; set; }
        public virtual DbSet<Ideatag> Ideatags { get; set; }
        public virtual DbSet<RoleMapping> RoleMappings { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<S3AttachmentContainer> S3AttachmentContainer { get; set; }
        public virtual DbSet<UserAuthentication> UserAuthentications { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<IdeaIntellectualProperty> IdeaIntellectualProperties { get; set; }
        public virtual DbSet<IdeaArchiveHistory> IdeaArchiveHistories { get; set; }
        public virtual DbSet<IdeaLog> IdeaLogs { get; set; }
    }
}
