//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdeaDatabase.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdeaAssignment
    {
        public int IdeaAssignmentsId { get; set; }
        public int IdeaId { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public int ReviewByUserId { get; set; }
    
        public virtual Idea Idea { get; set; }
        public virtual User User { get; set; }
    }
}
