//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdeaDatabase.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdeaArchiveHistory
    {
        public int IdeaArchiveHistoryId { get; set; }
        public Nullable<int> IdeaId { get; set; }
        public string Description { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> ArchiveDate { get; set; }
    
        public virtual Idea Idea { get; set; }
        public virtual User User { get; set; }
    }
}
