//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdeaDatabase.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdeaStatusLog
    {
        public int IdeaStatusLogId { get; set; }
        public int IdeaId { get; set; }
        public int IdeaState { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifiedByUserId { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Idea Idea { get; set; }
    }
}
