//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdeaDatabase.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class S3AttachmentContainer
    {
        public int S3AttachmentContainerId { get; set; }
        public int IdeaId { get; set; }
        public string AttachedFileName { get; set; }
        public string FolderName { get; set; }
        public System.DateTime UploadDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Idea Idea { get; set; }
    }
}
