//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdeaDatabase.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAuthentication
    {
        public int UserAuthenticationId { get; set; }
        public int UserId { get; set; }
        public string TokenMD5 { get; set; }
        public string Token { get; set; }
        public string LanguageCode { get; set; }
        public string CountryCode { get; set; }
        public Nullable<bool> IsHPID { get; set; }
        public string ClientApplication { get; set; }
        public string ClientVersion { get; set; }
        public string ClientPlatform { get; set; }
        public string CallerId { get; set; }
        public string ClientId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string UseCaseGroup { get; set; }
        public Nullable<System.DateTime> LogoutDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
