//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdeaDatabase.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.IdeaAssignments = new HashSet<IdeaAssignment>();
            this.IdeaCategories = new HashSet<IdeaCategory>();
            this.IdeaComments = new HashSet<IdeaComment>();
            this.IdeaCommentDiscussions = new HashSet<IdeaCommentDiscussion>();
            this.IdeaContributors = new HashSet<IdeaContributor>();
            this.Ideas = new HashSet<Idea>();
            this.IdeaSubscribers = new HashSet<IdeaSubscriber>();
            this.Ideatags = new HashSet<Ideatag>();
            this.RoleMappings = new HashSet<RoleMapping>();
            this.UserAuthentications = new HashSet<UserAuthentication>();
            this.IdeaIntellectualProperties = new HashSet<IdeaIntellectualProperty>();
            this.IdeaArchiveHistories = new HashSet<IdeaArchiveHistory>();
            this.IdeaLogs = new HashSet<IdeaLog>();
        }
    
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailAddress { get; set; }
        public string SessionToken { get; set; }
        public string RefreshToken { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string ProfileId { get; set; }
        public Nullable<int> IsacId { get; set; }
        public Nullable<bool> IsSynchronized { get; set; }
        public Nullable<bool> ActiveHealth { get; set; }
        public string HPIDprofileId { get; set; }
        public string PrimaryUse { get; set; }
        public string CompanyName { get; set; }
        public Nullable<bool> EmailConsent { get; set; }
        public Nullable<System.DateTime> RefreshTokenExpireIn { get; set; }
        public Nullable<int> RefreshTokenType { get; set; }
        public Nullable<bool> SmartFriend { get; set; }
        public string OrigClientId { get; set; }
        public string Locale { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IdeaAssignment> IdeaAssignments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IdeaCategory> IdeaCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IdeaComment> IdeaComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IdeaCommentDiscussion> IdeaCommentDiscussions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IdeaContributor> IdeaContributors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Idea> Ideas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IdeaSubscriber> IdeaSubscribers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ideatag> Ideatags { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoleMapping> RoleMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserAuthentication> UserAuthentications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IdeaIntellectualProperty> IdeaIntellectualProperties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IdeaArchiveHistory> IdeaArchiveHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IdeaLog> IdeaLogs { get; set; }
    }
}
